services:
  - type: web
    name: canadian-immigration-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:server
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"